name: push-build-deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo
      uses: actions/checkout@v4
    - name: uses python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11' 
    - run: python first.py
