name: hello-world

on: push

jobs:
  hello-world-jobs:

    runs-on: ubuntu-latest

    steps:
      - name: this is an optional name
        uses: actions/checkout@v4
      - run: echo "$(cat first.py)"
